### ISSUE TITLE
Investigate cursor and text alignment

### ISSUE THREAD

**Issue by Androlite83** [spiralofhope/SuperDuperMacro#18]
As of 8.2, the cursor and text doesn't aligned to the screen. 

See:
- #3 - Fix child window scaling
- https://github.com/spiralofhope/_DevPad.GUI/issues/1

**Comment by spiralofhope** [comment]
Thanks for mentioning this.

I've taken a break from the game, but I can log in with a trial and check this out.  I hope this is a simple fix because this is a familiar problem.

**Comment by spiralofhope** [comment]
I only see one issue:

- Make a large item
- Scroll to the bottom
- Highlight some text

The highlighting isn't lined up with the text.

Could you describe your issue more thoroughly for me?

**Comment by Androlite83** [comment]
That is exactly the problem. The cursor to type doesn't match the screen display.

**Comment by Androlite83** [comment]
> 
> 
> I only see one issue:
> 
>     * Make a large item
> 
>     * Scroll to the bottom
> 
>     * Highlight some text
> 
> 
> The highlighting isn't lined up with the text.
> 
> Could you describe your issue more thoroughly for me?

It is indeed what you mentioned. 

Clicking a long page doesn't bring cursor aligned to what is being clicked. Highlighting text doesn't show up properly on screen.

However, the cursor is aligned to the screen when typing.

**Comment by spiralofhope** [comment]
Thanks for the update.

Later today I'll look into this more closely.

**Comment by spiralofhope** [comment]
Sorry, I spent more than an hour and have absolutely no idea what's going on.

Maybe this is an issue on Blizzard's end?

**Comment by Androlite83** [comment]
Sorry to bump this issue up. Anyone can help please?

**Comment by Androlite83** [comment]
Can close this now. Happy days problem resolved itself in 8.25.

**Comment by spiralofhope** [comment]
In the past, there was a similar alignment problem which authors couldn't solve.  It looks like this was the same thing showing up again.

Well I'm glad they fixed it!
