### ISSUE TITLE
Backport to TBC

### ISSUE THREAD

**Issue by Macumbafeh** [spiralofhope/SuperDuperMacro#25]
Is it possible to backport it for TBC?

The 1.8 version work. But you can't drag the icon on action bar : /

Thanks

**Comment by spiralofhope** [comment]
Sorry I'm not a programmer, so I doubt I can help.

The old versions worked for old WoW, so you might be able to go back to an even earlier version.  I don't know if the original author's repository has additional non-release changes that might fix your problem (perhaps slightly after your 1.8)

https://github.com/hypehuman/super-duper-macro

As a workaround, perhaps you can make regular macros for your action bars and use `/click` to reference superdupermacro macros.

**Comment by Macumbafeh** [comment]
Thanks you i'll try it !
