### ISSUE TITLE
[classic] LUA error - compare two nil values 

### ISSUE THREAD

**Issue by chrisblossom** [spiralofhope/SuperDuperMacro#28]
The following LUA error occurs every time I login WoW Classic:

```lua
Date: 2020-08-03 17:04:17
ID: 1
Error occured in: Global
Count: 1
Message: ...face\AddOns\SuperDuperMacro\SuperDuperMacro_Core.lua line 499:
   attempt to compare two nil values
Debug:
   [C]: ?
   ...face\AddOns\SuperDuperMacro\SuperDuperMacro_Core.lua:499: sdm_CompareVersions()
   ...face\AddOns\SuperDuperMacro\SuperDuperMacro_Core.lua:39:
      ...face\AddOns\SuperDuperMacro\SuperDuperMacro_Core.lua:30
```

Any ideas how to fix?

Thanks!

**Comment by spiralofhope** [comment]
I've seen that; it has to do with checking versions of the addon to import from old savedvariables.. I thought I had fixed that but I'll have to take another look.

**Comment by chrisblossom** [comment]
If there is anything I can do to help let me know. I would put a PR in to try and fix but am very unfamiliar with LUA.

**Comment by spiralofhope** [comment]
Well crap, I made a small mistake when I last investigated this.  It should be fixed in `retail_8.3.0.1,_classic_1.13.5.2` now.

https://github.com/spiralofhope/SuperDuperMacro/releases/tag/retail_8.3.0.1%2C_classic_1.13.5.2

**Comment by chrisblossom** [comment]
Looks like that fixed it! Thanks for getting that done so quickly!

**Comment by spiralofhope** [comment]
I'm glad it works.

Also, what does "put a PR in" mean?  I looked around and can find usage with no real context to explain it.

**Comment by chrisblossom** [comment]
I PR in github terms means Pull Request. Basically if I knew how I would have fixed the code on my end then used github's pull request feature to ask you to merge the fixes into this repository.

Can read more about pull requests here: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests
