### ISSUE TITLE
SuperDuperMacro Not Allowing Creation of Macros

### ISSUE THREAD

**Issue by ghost** [spiralofhope/SuperDuperMacro#33]
**ERROR:** "You** must be logged into the appropriate character to run this."

**NOTE:** All other addons disabled.

![WoWScrnShot_111620_185917](https://user-images.githubusercontent.com/69120722/99341012-f4328600-283d-11eb-991d-67a9a95e74a2.jpg)

**FIXED:** Updating to the beta version of SDM fixed the problem, however macro edit name/icon is not letting me select an icon -

![WoWScrnShot_111620_190431](https://user-images.githubusercontent.com/69120722/99341394-a1a59980-283e-11eb-8eec-d339d6bf5b5a.jpg)

**Comment by spiralofhope** [comment]
I'm glad the beta is working for you; I'll make a point to package it soon once I take a look at the other issue.

I made #34 for that
